project:
  type: website
  output-dir: docs

website:
  title: "The Data Chanalyst"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: researcher.qmd
        text: The Researcher
      - href: artist.qmd
        text: The Artist
      - href: writer.qmd
        text: The Writer
      - href: publications.qmd
        text: Publications
      - href: projects.qmd
        text: Projects
      

format:
  html:
    theme:
      - vapor
      #- quartz
    css: styles.css
    toc: true

editor: visual

