---
title: "DataChanalyst"
---

# Anthea (Andy) Chan, MA

## Senior Research Manager at the Global Lab at Coqual

+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ### The Artist                                                                                                                                                                                                                                             | ### The Researcher                                                                                                                                                                                                                                                         | ### The Writer                                                                                                                                                      |
+:==========================================================================================================================================================================================================================================================:+:==========================================================================================================================================================================================================================================================================:+:===================================================================================================================================================================:+
| I am a lifelong painter and artist, having dabbled in mediums both digital and traditional. I use Procreate on the iPad, oil paint and watercolor, or just my sketchbook and a pencil. I visually bring to life the fantasy worlds that reside in my head. | I'm a researcher and data analyst with 8+ years of experience turning complex survey and behavioral data into insights that inform organizational decision-making. My work sits at the intersection of rigorous statistical methods and human-centered research questions. | I blog about social issues, online trends, and the academic research rabbit holes I fall down. I am also working on an epic 6-part fantasy series on my spare time. |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| To do: build gallery                                                                                                                                                                                                                                       | To do: link to project gallery, rmarkdown files                                                                                                                                                                                                                            | To do: link to blog                                                                                                                                                 |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
