---
title: "Publications"
---

## 2025

### Journal Article

Kim, V., Siracusa, L., Silvert, L., **Chan, A.,** & Brewster, M.E. (2025). ["Oh, Are You Just Kinky in Bed?”: Tying Together the Personal, Interpersonal, and Sociocultural Dimensions of BDSM](https://doi.org/10.51681/1.1112), Journal of Positive Sexuality, 11(1), 34-52.

### Other Writing

Coqual. (2025). [*The Neuroinclusion Imperative: Unlocking Untapped Potential*](https://coqual.org/reports/the-neuroinclusion-imperative/)

Coqual. (2025). [*Pride Under Pressure: Charting a Course for Global LGBTQ+ Workplace Inclusion*](https://coqual.org/reports/pride-under-pressure/)*.*

**Chan, A**. (2025, June 24). [Pride Under Pressure: Notes from a Queer Millennial](https://coqual.org/blog/pride-under-pressure-notes-from-a-queer-millennial/). *Coqual Signals from the Lab.*

## 2024

### Journal Article

### Other Writing

Coqual. (2024). [*More than a Monolith: The Advancement of Hispanic and Latino/a Talent.*](https://coqual.org/reports/more-than-a-monolith/)

## 2023

### Journal Article

Coleman, P.T. & **Chan, A.** (2023). [Conflict + Anxiety = Turmoil! Introducing a Measure of Conflict Derailers](https://doi.org/10.1111/nejo.12427). *Negotiation Journal, 39*(2), 137-173*.*

Brewster, M.E., Motulsky, W., **Chan, A.,** & Berg, E., & Kim, V. (2023). [Romantic attachment, LGB minority stress, and mental health](https://doi.org/10.1080/10538720.2023.2286367). Journal of Gay & Lesbian Social Services, 1-22.

### Other Writing

Coqual. (2023). [*Challenging Norms: A Global Analysis of Gender at Work*](https://coqual.org/reports/challenging-norms/)

Coqual. (2023). [*Strangers at Home: The Asian and Asian American Professional Experience*](https://coqual.org/reports/strangers-at-home/)*.*

Coqual. (2023). [*Black Equity Index: Tracking commitment to racial equity in the workplace*](https://coqual.org/wp-content/uploads/2023/12/BEI-White-Paper-2023.pdf)*.*

## 2022

### Journal Article

Cook, S. H., Wood, E. P., **Chan, A.,** Rambarran, S., & Aguilera, L. (2022). [Race moderates the association between adult attachment avoidance and the cortisol awakening response among young sexual minority men](https://doi.org/10.1016/j.psyneuen.2022.105899). *Psychoneuroendocrinology*, 145, 105899.

### Other Writing

Coqual. (2022). [*Being Black in the United Kingdom*](https://coqual.org/reports/being-black-in-the-united-kingdom/)*.*

Coqual. (2022). [*Equity and Ethnicity at Work: A Global Exploration*](https://coqual.org/reports/equity-and-ethnicity-at-work/)*.*

Coqual. (2022). [*Black Equity Index: Tracking commitment to racial equity in the workplace*](https://coqual.org/wp-content/uploads/2022/05/BEI-white-paper-FINAL-05.24.pdf)*.*

## 2021

### Journal Article

Brewster, M., Velez, B., Sawyer, J., Motulsky, W., **Chan, A.,** & Kim, V. (2021). [Family religiosity, support, and psychological well-being for sexual minority atheist individuals](https://doi.org/10.1037/rel0000356). *Psychology of Religion and Spirituality, 13*(3), 266–275.

### Other Writing

Brewster, M., Motulsky, W., & **Chan, A.** (2021). [Intersectional Atheisms: Race, Gender, and Sexuality](https://www.cambridge.org/core/books/abs/cambridge-history-of-atheism/intersectional-atheisms-race-gender-and-sexuality/004964982E395A2CFD2DF8B44AA4D9CB). In M. Ruse (Author) & S. Bullivant (Ed.), *The Cambridge History of Atheism* (pp. 1059-1079). Cambridge: Cambridge University Press.

Coleman, P.T., Hughes, C., & **Chan, A.** (2021, June 9). [*Lessons from the most politically tolerant places in the US*](https://thehill.com/opinion/campaign/557430-lessons-from-the-most-politically-tolerant-places-in-the-us)*.* The Hill.

**Chan, A.** (2021, May 28). [*What Can We Learn from the 1%? Methods and Analyses.*](https://icccr.tc.columbia.edu/blog/what-can-we-learn-from-the-1-methods-and-analyses/) The Morton Deutsch International Center for Cooperation and Conflict Resolution Blog.

## 2020

### Journal Article

Xu, S., **Chan, A.,** Lorber, M., & Chase, J.P. (2020). [Using security questions to link participants in longitudinal data collection](https://doi.org/10.1007/s11121-019-01080-8). *Prevention Science, 21*, 194-202*.*

Breslow, A.S., Sandil, R., Brewster, M.E., Parent, M.C., **Chan, A.,** Yucel, A., Bensmiller, N., & Glaeser, E. (2020). [Adonis on the apps: Online objectification, self-esteem, and sexual minority men](http://dx.doi.org/10.1037/men0000202). *Psychology of Men & Masculinities, 21*(1), 25-35.

### Other Writing

**Chan, A.** (2020, May 27). [*Conflict Anxiety at Home*](https://icccr.tc.columbia.edu/blog/conflict-anxiety-at-home-ac-blog/)*.*  The Morton Deutsch International Center for Cooperation and Conflict Resolution Blog.

Coleman, P.T., & **Chan, A.** (2020, May 26). [*How to Manage COVID and Conflict in Our Homes and Workplaces.*](https://news.climate.columbia.edu/2020/05/26/covid-conflict-anxiety-survey/) Columbia Climate School’s State of the Planet.

## 2015

### Journal Article

**Chan, A.,** Alif, A., & Nelson, B.S., (2015). [The impact of family and demographic factors on the intergenerational transmission of violence.](https://wp.nyu.edu/steinhardt-appsych_opus/the-impact-of-family-and-demographic-factors-on-intergenerational-transmission-of-violence/) *NYU Applied Psychology Online Publication of Undergraduate Studies, 8.* 26-31.
